---
title: "KJ_final"
author: "Hanon Mcshea"
date: "7/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0 Setting up R

Install the necessary packages and load their libraries

```{r warning=FALSE, message=FALSE}
pkgs_needed = c("dplyr", "ade4", "ggplot2", "ggpubr", "lmodel2")
letsinstall = setdiff(pkgs_needed, installed.packages()) 
if (length(letsinstall) > 0) {
  BiocManager::install(setdiff(pkgs_needed, installed.packages()))
}

#pkgs_needed = c("Rpdb", "rgl", "Rcpp", "tidyverse", "Biostrings", "RColorBrewer", "magrittr", "plyr", "reshape2", "ade4", "ggplot2", "rowr", "ggpubr", "backports", "lmodel2")

library("dplyr")
library("ade4")
library("ggplot2")
library("ggpubr")
library("lmodel2")

#library("Rpdb")
#library("Rcpp")
#library("rgl")
#library("rowr")
#library("backports")
#library("curl")

remove.packages(c("ggplot2", "data.table"))
install.packages('Rcpp', dependencies = TRUE)
install.packages('ggplot2', dependencies = TRUE)
install.packages('data.table', dependencies = TRUE)
```

## 1 Loading data and computing gain/loss ratios and D values

Load and wrangle the substitutions files.

### 1.1 Count substitutions

```{r Mouse}

Mouse <- read.csv(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Mouse_substitutions.csv",  col.names=c("EnsemblMouseReference","Derived","Ancestral","AASequence","Position","AASequencePolymorphismsMasked","DNASequence","ExonReference","ExonMore")) 

#dMouse = unique(Mouse, by=c("Derived","Ancestral","ExonReference")) #this does not work for some reason, returns the same dim as unique(Mouse)
#ddMouse = unique(Mouse[,2:9]) #this does work but does not preserve first col
#ddMouse = subset(Mouse, select=c(Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore)) #doesn't work
#dddMouse = subset(ddMouse, !duplicated(ddMouse)) #does work but does not preserve first col

#dxMouse <- Mouse[!duplicated(Mouse$EnsemblMouseReference), ] #cuts too much
#df <-Mouse
#df %>% filter(!duplicated(cbind(Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore))) #doesn't work

uMouse <- distinct(Mouse, Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore, .keep_all=T) #best option because it preserves first col

mdist = as.data.frame(table(uMouse$ExonReference))
summary(mdist$Freq)
```

```{r Rat}
Rat <- read.csv(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Rat_substitutions.csv",  col.names=c("EnsemblMouseReference","Derived","Ancestral","AASequence","Position","AASequencePolymorphismsMasked","DNASequence","ExonReference","ExonMore")) 

uRat <- distinct(Rat, Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore, .keep_all=T)

rdist = as.data.frame(table(uRat$ExonReference))
summary(rdist$Freq)
```

```{r Chimp}
Chimp <- read.csv(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Chimp_substitutions.csv",  col.names=c("EnsemblMouseReference","Derived","Ancestral","AASequence","Position","AASequencePolymorphismsMasked","DNASequence","ExonReference","ExonMore")) 

uChimp <- distinct(Chimp, Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore, .keep_all=T)

cdist = as.data.frame(table(uChimp$ExonReference))
summary(cdist$Freq)
```

```{r Human}
Human <- read.csv(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Human_substitutions.csv",  col.names=c("EnsemblMouseReference","Derived","Ancestral","AASequence","Position","AASequencePolymorphismsMasked","DNASequence","ExonReference","ExonMore")) 

uHuman <- distinct(Human, Derived, Ancestral, AASequence, Position, AASequencePolymorphismsMasked, DNASequence, ExonReference, ExonMore, .keep_all=T)

hdist = as.data.frame(table(uHuman$ExonReference))
summary(hdist$Freq)
```

```{r calculate D}
#function to calculate D from uAnimal dataframe
Dcalc = function(x) {
  hder = as.data.frame(table(x$Derived), stringsAsFactors=FALSE) %>% rename(der_count = Freq)
  hanc = as.data.frame(table(x$Ancestral), stringsAsFactors=FALSE) %>% rename(anc_count = Freq)
  hcounts = cbind(hder, anc_count=hanc$anc_count) 
  hcounts = mutate(hcounts, ratio = der_count/anc_count, noratio =
                     (der_count-anc_count)/(der_count+anc_count), study = "HM")
hcounts = hcounts[-1,] %>% rename(aa=Var1)
return(hcounts)
}

Derr = function(G,L) {
  err = sqrt((2*G*L)/((G+L)^3))
  return(err)
}

#calculate D for the 4 organisms, as well as error
Dmouse <- Dcalc(uMouse) %>% rename(mouse_noratio=noratio) %>% mutate(mouse_error = Derr(der_count,anc_count))
Drat <- Dcalc(uRat) %>% rename(rat_noratio=noratio) %>% mutate(rat_error = Derr(der_count,anc_count))
Dchimp <- Dcalc(uChimp) %>% rename(chimp_noratio=noratio) %>% mutate(chimp_error = Derr(der_count,anc_count))
Dhuman <- Dcalc(uHuman) %>% rename(human_noratio=noratio) %>% mutate(human_error = Derr(der_count,anc_count)) #human error, get it? haha

#create rodent and primate dataframes
Rodent <- rbind(uMouse, uRat)
Primate <- rbind(uChimp, uHuman)

mrhc <- cbind(Dmouse[,c(1,5,7)], Drat[,c(5,7)], Dhuman[,c(5,7)], Dchimp[,c(5,7)])
write.csv(mrhc, file="C:/Users/Hannah/Documents/Github/KJ/Final/MRHC.txt", quote=FALSE, row.names=FALSE)

#calculate D for rodents and primates
Dprimate <- Dcalc(Primate) %>% rename(Pnoratio=noratio) %>% mutate(Perror = Derr(der_count,anc_count))
Drodent <- Dcalc(Rodent) %>% rename(Rnoratio=noratio) %>% mutate(Rerror = 1/sqrt(der_count+anc_count))

#write files with the normalized fluxes and associated errors for primates and rodents
write.csv(Dprimate[,c(1,5,7)], file="C:/Users/Hannah/Documents/Github/KJ/Final/Dprimate.txt", quote=FALSE, row.names=FALSE)
write.csv(Drodent[,c(1,5,7)], file="C:/Users/Hannah/Documents/Github/KJ/Final/Drodent.txt", quote=FALSE, row.names=FALSE)
```

### 1.2 Calculate shared and species component

```{r read in D data files}
#read in rodent D values
dR <- read.delim(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Drodent.txt", header=TRUE, stringsAsFactors=FALSE, sep=",")

#read in primate D values
dP <- read.delim(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Dprimate.txt", header=TRUE, stringsAsFactors=FALSE, sep=",")

#make a table with both
dB <- cbind(dR, dP)
#clean it up
DD <- dB[,c(1:3,5,6)]
DD

#plot primate vs rodent
Fig1pre <- ggplot(DD, aes(x=Pnoratio, y=Rnoratio))+
  labs( x = "Primate Amino Acid Flux D", y = "Rodent Amino Acid Flux D") +
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) +
  #theme(aspect.ratio=1) +
  geom_point(size=3) +
  geom_errorbar(DD, mapping = aes(y=Rnoratio, ymin=Rnoratio-Rerror, ymax=Rnoratio+Rerror)) + geom_errorbarh(DD, mapping = aes(x=Pnoratio, xmin=Pnoratio-Perror, xmax=Pnoratio+Perror)) +
  theme(axis.title=element_text(size=24, face ="bold"), axis.text=element_text(size=18), panel.background = element_rect(fill = "white", colour = "grey50"),panel.grid.major = element_line(colour = "grey90"))#,panel.grid.minor = element_line(colour = "grey90")) 
  

Fig1pre
```

```{r fit model}
#calculate model regressions of rodent-on-primate, primate-on-rodent
fitI <- lm(Pnoratio ~ Rnoratio, data=DD)
fitflipI <- lm(Rnoratio ~ Pnoratio, data=DD)
#need a model II regresion

fitII <- lmodel2(Rnoratio ~ Pnoratio, data=DD, range.y="interval", range.x="interval", nperm=99)
reg <- fitII$regression.results

prs <- cor.test(DD$Pnoratio, DD$Rnoratio, method='spearman')
prp <- cor.test(DD$Pnoratio, DD$Rnoratio, method='pearson')

Fig1 <- Fig1pre + geom_abline(data=subset(reg, Method=="MA"), aes(intercept=Intercept, slope=Slope), color="red", size=2) + geom_text(aes(x = -0.2, y = 0.15, label = paste("R = ", signif(prs$estimate, digits=3), "\n p = ", signif(prs$p.value, digits=3))),size=6, color = "black")
Fig1

slope <- subset(reg, Method=="MA")$Slope
intercept <- subset(reg, Method=="MA")$Intercept
```

```{r calculate shared and species}
#calculate SPECIES COMPONENT: residuals between fluxes in P-R space and the model II regression
residuals_from_model_2 <- function(x,y,m,b){
  result<-((b + m*x - y))/sqrt(m**2+1)
  print(result*-1)
}

#my_residuals <- function(x,y,m,b){
#  result<-sqrt((y - m*x - b)^2+(x-((y-b)/m)^2))
#  print(result)
#}

#calculate SHARED COMPONENT: projection of fluxes in P-R space along the model II regression
projections_from_model_2 <- function(x,y,m,b){
  result<-sqrt(((x+m*y -m*b)/(m*m+1))**2+((m)*(x+m*y -m*b)/(m*m+1)+b)**2)
  print(result)
}

DD$residuals_m2<-residuals_from_model_2(DD$Pnoratio, DD$Rnoratio, slope, intercept)
DD$projections_m2<- projections_from_model_2(DD$Pnoratio, DD$Rnoratio, slope, intercept)
DD

#account for negative signs
DD[DD$aa=="A", "projections_m2"] <- -0.03258651
DD[DD$aa=="D", "projections_m2"] <- -0.04828818
DD[DD$aa=="E", "projections_m2"] <- -0.20779364
DD[DD$aa=="G", "projections_m2"] <- -0.05330564
DD[DD$aa=="K", "projections_m2"] <- -0.16506769
DD[DD$aa=="L", "projections_m2"] <- -0.05679737
DD[DD$aa=="P", "projections_m2"] <- -0.24578878
DD[DD$aa=="Q", "projections_m2"] <- -0.09350436
DD[DD$aa=="Y", "projections_m2"] <- -0.02058972

#Check that calculations were correct
Dang<-ggplot(DD, aes(x=projections_m2, y=residuals_m2))+
  labs( x = "Shared Flux", y = "Species Flux")+
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6)+
  geom_point(size=3)+theme(axis.title=element_text(size=24, face ="bold"),title=element_text(size=24, face ="bold"),axis.text=element_text(size=24),panel.background = element_rect(fill = "white", colour = "grey50"),panel.grid.major = element_line(colour = "grey90"),panel.grid.minor = element_line(colour = "grey90"))
Dang
```

```{r error on shared and species}
ellipse_error <- function(a,b,theta){
  result <- (a*b)/sqrt((b*cos(theta))^2 + (a*sin(theta))^2)
  print(result)
}
radslope <- (subset(reg, Method=="MA")$Angle)*(pi/180)
radnormal <- radslope+(0.5*pi)

DD$residual_error <- ellipse_error(DD$Perror, DD$Rerror, radnormal)
DD$projection_error <- ellipse_error(DD$Perror, DD$Rerror, radslope)

Dang_err <- Dang + geom_errorbar(DD, mapping = aes(ymin=residuals_m2-residual_error, ymax=residuals_m2+residual_error)) + geom_errorbarh(DD, mapping = aes(xmin=projections_m2-projection_error, xmax=projections_m2+projection_error))
Dang_err

write.csv(DD[,c(1,7,9)], file="C:/Users/Hannah/Documents/Github/KJ/Final/Shared.txt", quote=FALSE, row.names=FALSE)

write.csv(DD[,c(1,6,8)], file="C:/Users/Hannah/Documents/Github/KJ/Final/Species.txt", quote=FALSE, row.names=FALSE)

write.csv(DD, file="C:/Users/Hannah/Documents/Github/KJ/Final/DD_SS_err.txt", quote=FALSE, row.names=FALSE)
```

```{r CAIS slopes}
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa <- read.delim(file = "C:/Users/Hannah/Documents/Github/KJ/Final/Drodent.txt", header=TRUE, stringsAsFactors=FALSE, sep=",")







```
